
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/nikhilsbhat/renderer/version.Version={{.Version}} -X github.com/nikhilsbhat/renderer/version.Env={{.Env.BUILD_ENVIRONMENT}} -X github.com/nikhilsbhat/renderer/version.BuildDate={{.Date}} -X github.com/nikhilsbhat/renderer/version.Revision={{.Commit}} -X github.com/nikhilsbhat/renderer/version.GoVersion={{.Env.GOVERSION}} -X github.com/nikhilsbhat/renderer/version.Platform={{ .Os }}/{{ .Arch }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
